### ISSUE TITLE
IPOPT

### ISSUE THREAD

**Issue by GithubMingEnter** [Geonhee-LEE/mpc_ros#35]
hello 
when I use mpc_ros local planner plugin, I find a error
```c++
src/mpc_ros/mpc_ros/include/cppad/utility/error_handler.hpp:206:
 static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
```
please tell me how to handle it
thanks

**Comment by Geonhee-LEE** [comment]
Hi, @GithubMingEnter.
I have never see that error. Did you follow the [installation guide](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/assets/document/ipopt_install/ipopt_arm_install_tutorial.md)?

**Comment by zhaohaowu** [comment]
> Hi, @GithubMingEnter. I have never see that error. Did you follow the [installation guide](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/assets/document/ipopt_install/ipopt_arm_install_tutorial.md)?

Hi, I find the same error
`vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 476 in the file 
    /home/zhw/duo/test/src/mpc_ros/mpc_ros/include/cppad/utility/vector.hpp
tracking_reference_trajectory: /home/zhw/duo/test/src/mpc_ros/mpc_ros/include/cppad/utility/error_handler.hpp:206: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
`
I have followed the installation guide, but I can't run `./get.Mumps` and `./get.Metis` because the website can't be opened.

**Comment by zhaohaowu** [comment]
> Hi, @GithubMingEnter. I have never see that error. Did you follow the [installation guide](https://github.com/Geonhee-LEE/mpc_ros/blob/melodic/assets/document/ipopt_install/ipopt_arm_install_tutorial.md)?

Hi, I find the same error
`
vector: index greater than or equal vector size Error detected by false result for i < length_ at line 476 in the file /home/zhw/duo/test/src/mpc_ros/mpc_ros/include/cppad/utility/vector.hpp tracking_reference_trajectory: /home/zhw/duo/test/src/mpc_ros/mpc_ros/include/cppad/utility/error_handler.hpp:206: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion false' failed.
`
I have followed the installation guide, but I can't run.**/get.Mumps** and**./get.Metis** because the website can't be opened.

**Comment by sumingzs11** [comment]
I have followed the installation guide, but I can't run./get.Mumps and**./get.Metis** because the website can't be opened

**Comment by sumingzs11** [comment]
I have followed the installation guide, but I can't run./get.Mumps and**./get.Metis** because the website can't be opened
I have the same problem.

**Comment by Geonhee-LEE** [comment]
@zhaohaowu  @sumingzs11  could you upload the images for installation process for coin-or?

**Comment by sumingzs11** [comment]
Thanks for you answer. I have solved the problem. I think there is an error in Mumps and Metis. When we execute " ./get.Mumps", it ouccured an HTTP error. The method is to use the ipopt package concluding these and  then make and make install.

**Comment by DeepDuke** [comment]
I met this problem too. I also cannot run `./get.Mumps` and `./get.Metis` . @sumingzs11 how do you solve this?

**Comment by sumingzs11** [comment]
@DeepDuke

**Comment by sumingzs11** [comment]
@DeepDuke 
you can give me an e-mail address so that I can give you the package.

**Comment by DeepDuke** [comment]
@sumingzs11 My email is czm.hit@gmail.com. Thank you!

**Comment by sumingzs11** [comment]
@DeepDuke 
There may be some error because I have sent the package three times. Each time my mail has been returned, because it is recognized as spam.

**Comment by DeepDuke** [comment]
@sumingzs11 Sorry, please send to my another email 11849041@mail.sustech.edu.cn

**Comment by DeepDuke** [comment]
@sumingzs11 I tried your package, it works. Thank you!

**Comment by zhaohaowu** [comment]
> @DeepDuke you can give me an e-mail address so that I can give you the package.
Can you send me the package too. My Email address is 2356940823@qq.com. Thank you!

**Comment by zrd1234** [comment]
> @DeepDuke you can give me an e-mail address so that I can give you the package.

Can you send me the package too. My Email address is 779258494@qq.com. Thank you!

**Comment by slamlixiaodong** [comment]
Can you send me the package too. My Email address is [dxchinaedu@163.com](mailto:dxchinaedu@163.com). Thank you!

**Comment by slamlixiaodong** [comment]
> > @DeepDuke you can give me an e-mail address so that I can give you the package.
> 
> Can you send me the package too. My Email address is [779258494@qq.com](mailto:779258494@qq.com). Thank you!

Can you send me the package too. My Email address is [dxchinaedu@163.com](mailto:dxchinaedu@163.com). Thank you!

**Comment by Raychan382** [comment]
@sumingzs11 Can you send me the package too. My Email address is 1654145253@qq.com. Thank you!

**Comment by Raychan382** [comment]
@DeepDuke Can you send me the package too. My Email address is [1654145253@qq.com](mailto:1654145253@qq.com). Thank you!
